In [1]:
import pandas as pd
import numpy as np

In [24]:
# Import the data
preterm_data = pd.read_csv("../output/tarca_et_al_2021/GSE150167-term+preterm/full_data_merged.csv")
term_data = pd.read_csv("../output/tarca_et_al_2021/GSE206454-term-only/full_data_merged.csv")

# Preprocessing

In [25]:
# Add GEO accessions
preterm_data['GEO_accession'] = 'GSE150167'
term_data['GEO_accession'] = 'GSE206454'

# Add the Group column to the term data and label as controls
term_data['Group'] = 'Control'

In [4]:
# Are all the Organism values the same and coming from human samples? Yes, they are. 
#term_data.value_counts('Organism_x')
#term_data.value_counts('Organism_y')

In [26]:
# Remove redundant columns 
term_data = term_data.drop(['Organism_x', 'Organism_y', 'ID', 'ID_REF', 'SPOT_ID', 'SeqIdVersion', 'Type', 'Units'], axis = 1)
preterm_data = preterm_data.drop(['ID', 'PT_LIST', 'Sample_channel_count', 'Tissue', 'DiagnosisGA', 'SPOT_ID'], axis = 1)
preterm_data

,Accession,ID_REF,Log2RFU,SeqId,Target,TargetFullName,UniProt,ENTREZ_GENE_ID_LIST,EntrezGeneSymbol,Title,Sample_type,GA,GA_delivery,Group,Individual,GEO_accession
0,GSM4525301,SL000318,12.579057,2182-54_1,C4b,Complement C4b,P0C0L4 P0C0L5,"720,721",C4A C4B,s132,protein,16.9,40.1,Control,10273,GSE150167
1,GSM4525301,SL002662,10.688600,2190-55_1,Coagulation Factor XI,Coagulation Factor XI,P03951,2160,F11,s132,protein,16.9,40.1,Control,10273,GSE150167
2,GSM4525301,SL003168,10.516685,2192-63_10,CTACK,C-C motif chemokine 27,Q9Y4X3,10850,CCL27,s132,protein,16.9,40.1,Control,10273,GSE150167
3,GSM4525301,SL000403,15.616368,2201-17_6,Endostatin,Endostatin,P39060,80781,COL18A1,s132,protein,16.9,40.1,Control,10273,GSE150167
4,GSM4525301,SL000591,8.400026,2211-9_6,TIMP-1,Metalloproteinase inhibitor 1,P01033,7076,TIMP1,s132,protein,16.9,40.1,Control,10273,GSE150167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236245,GSM4525510,SL010516,13.875874,5488-74_3,SRCN1,Proto-oncogene tyrosine-protein kinase Src,P12931,6714,SRC,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236246,GSM4525510,SL010250,13.167904,5489-18_3,Stress-induced-phosphoprotein 1,Stress-induced-phosphoprotein 1,P31948,10963,STIP1,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236247,GSM4525510,SL010384,11.996968,5490-53_3,Testican-1,Testican-1,Q08629,6695,SPOCK1,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236248,GSM4525510,SL010471,9.221829,5491-12_3,Testican-2,Testican-2,Q92563,9806,SPOCK2,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236249,GSM4525510,SL009790,11.028942,5494-52_3,RUXF,Small nuclear ribonucleoprotein F,P62306,6636,SNRPF,s469,protein,29.7,33.3,sPTD,9754,GSE150167

In [27]:
# Harmonize the column names
preterm_data = preterm_data.rename(columns={'ENTREZ_GENE_ID_LIST': 'EntrezGeneID'})
term_data = term_data.rename(columns={'SomaId': 'ID_REF'})

In [28]:
# Add GA_delivery column and fill with NaNs
term_data['GA_delivery'] = 'NaN'
term_data

,Accession,Log2RFU,SeqId,ID_REF,TargetFullName,Target,UniProt,EntrezGeneID,EntrezGeneSymbol,Title,Sample_type,GA,Individual,GEO_accession,Group,GA_delivery
0,GSM6254314,642.7,10000-28,SL019233,Beta-crystallin B2,CRBB2,P43320,1415,CRYBB2,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
1,GSM6254314,314.7,10001-7,SL002564,RAF proto-oncogene serine/threonine-protein ki...,c-Raf,P04049,5894,RAF1,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
2,GSM6254314,166.3,10003-15,SL019245,Zinc finger protein 41,ZNF41,P51814,7592,ZNF41,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
3,GSM6254314,568.4,10006-25,SL019228,ETS domain-containing protein Elk-1,ELK1,P19419,2002,ELK1,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
4,GSM6254314,401.4,10008-43,SL019234,Guanylyl cyclase-activating protein 1,GUC1A,P43080,2978,GUCA1A,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3806860,GSM6254832,1416.4,9993-11,SL019212,Zinc finger protein 264,ZN264,O43296,9422,ZNF264,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806861,GSM6254832,1593.0,9994-217,SL019217,Potassium-transporting ATPase subunit beta,ATP4B,P51164,496,ATP4B,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806862,GSM6254832,7279.9,9995-6,SL013164,Deoxyuridine 5'-triphosphate nucleotidohydrola...,DUT,P33316,1854,DUT,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806863,GSM6254832,17454.6,9997-12,SL019215,UBX domain-containing protein 4,UBXN4,Q92575,23190,UBXN4,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806864,GSM6254832,3188.0,9999-1,SL019231,Interferon regulatory factor 6,IRF6,O14896,3664,IRF6,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN

In [29]:
# Filter the term dataset to only contain entrez gene symbols present in preterm dataset
filtered_term_data = term_data[term_data['EntrezGeneSymbol'].isin(preterm_data['EntrezGeneSymbol'])]
filtered_term_data

,Accession,Log2RFU,SeqId,ID_REF,TargetFullName,Target,UniProt,EntrezGeneID,EntrezGeneSymbol,Title,Sample_type,GA,Individual,GEO_accession,Group,GA_delivery
67,GSM6254314,47148.9,10382-1,SL006803,Angiopoietin-related protein 3,ANGL3,Q9Y5C1,27329,ANGPTL3,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
69,GSM6254314,1503.3,10391-1,SL006803,Angiopoietin-related protein 3,ANGL3,Q9Y5C1,27329,ANGPTL3,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
93,GSM6254314,402.8,10457-3,SL004861,Interleukin-18 receptor accessory protein,IL-18 Rb,O95256,8807,IL18RAP,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
94,GSM6254314,2720.4,10460-1,SL006029,Chitotriosidase-1,Chitotriosidase-1,Q13231,1118,CHIT1,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
99,GSM6254314,1446.9,10472-53,SL004145,Tumor necrosis factor receptor superfamily mem...,HVEM,Q92956,8764,TNFRSF14,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3806722,GSM6254832,2406.6,9760-13,SL004716,Mitogen-activated protein kinase 9,JNK2,P45984,5601,MAPK9,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806737,GSM6254832,605.6,9787-23,SL007471,Collectin-12,COLEC12,Q5KU26,81035,COLEC12,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806769,GSM6254832,479.0,9845-33,SL008933,Protein DJ-1,PARK7,Q99497,11315,PARK7,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806819,GSM6254832,429.0,9925-56,SL005222,Scavenger receptor class F member 2,SREC-II,Q96GP6,91179,SCARF2,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN
3806836,GSM6254832,1461.8,9950-229,SL005195,Lymphocyte activation gene 3 protein,LAG-3,P18627,3902,LAG3,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN

# Normalization

In [30]:
# Restructure the datasets
filtered_term_data2 = filtered_term_data[['Accession', 'Target', 'Log2RFU']]
filtered_term_data3 = filtered_term_data2.drop_duplicates(subset = ['Accession', 'Target'], keep='last') # 753588 to 565710 (or 417276 if False)
filtered_term_data4 = filtered_term_data3.pivot(index = 'Accession', columns = 'Target', values = 'Log2RFU')
filtered_term_data4

Target,17-beta-HSD 1,3HIDH,4-1BB,4-1BB ligand,40S ribosomal protein SA,41,4EBP2,6-Phosphogluconate dehydrogenase,6Ckine,ABL1,...,sRAGE,sRANKL,sTie-1,sTie-2,suPAR,tPA,tau,"transcription factor MLR1, isoform CRA_b",uPA,vWF
Accession,,,,,,,,,,,,,,,,,,,,,
GSM6254314,625.2,426.3,220.0,166.8,3237.5,10125.4,207.9,7015.8,4064.3,263.8,...,490.5,1289.2,8679.6,1018.3,2541.2,1442.9,371.7,175.2,1393.5,32160.2
GSM6254315,637.2,459.5,260.6,168.5,913.2,10765.2,173.3,8258.4,4234.0,285.9,...,1213.7,1529.4,9802.5,818.8,3630.7,2099.7,212.4,207.4,1186.0,18962.6
GSM6254316,688.4,429.3,251.6,168.6,1881.0,28473.4,216.7,3622.1,7636.6,277.4,...,1337.8,1581.4,3405.8,992.7,2260.9,3427.5,293.6,208.5,714.9,35287.2
GSM6254317,626.8,444.1,286.1,171.3,849.3,19104.5,369.3,6170.4,3298.9,292.6,...,831.1,1365.3,6168.0,902.1,2859.0,1748.0,276.3,199.1,1163.4,17983.3
GSM6254318,646.6,414.9,261.8,162.3,1040.5,8332.2,157.8,8771.7,3585.8,275.9,...,2132.0,1190.8,8062.4,1278.4,3809.9,2615.8,369.2,179.1,2005.6,51166.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM6254828,603.9,443.4,272.8,194.5,842.9,8577.5,211.6,16246.4,3391.5,349.4,...,3509.4,644.4,6170.1,1010.9,3854.4,2846.5,275.6,210.8,1509.3,37396.6
GSM6254829,670.1,540.8,251.8,231.8,875.3,10094.5,174.2,11102.9,3828.2,299.7,...,967.2,1098.2,7607.7,980.0,3864.6,2472.9,328.6,264.6,1478.5,14580.6
GSM6254830,682.4,484.0,261.7,198.7,856.1,14247.7,172.7,11427.4,4159.3,338.7,...,575.9,1083.4,6530.9,981.5,3188.4,2286.9,410.8,206.1,2133.0,30576.1
GSM6254831,598.7,477.4,263.4,191.7,850.7,8123.9,194.6,18106.6,5230.5,303.2,...,451.9,1470.5,5311.8,821.9,3640.5,1582.2,279.4,211.4,1442.6,12734.3
GSM6254832,616.2,530.4,255.0,178.2,835.6,7913.6,161.8,2033.4,5807.3,309.4,...,294.7,1122.4,5880.8,812.1,3463.2,1617.4,426.9,183.5,1618.1,34563.7

In [31]:
# Calculate a rowsum (total intensity in each sample)
rowsums = filtered_term_data4.sum(axis = 1)
rowsums

# Identify the maximum rowsum (maximum total intensity across samples)
max_total = rowsums.max()
max_total

# Normalise the data
term_normalised = filtered_term_data4.div(rowsums, axis = 0).mul(max_total) # normalized_sample = (sample / rowsum) * max_total
term_normalised

# Log2 transform the data to stabilise the variance
term_log2 = np.log2(term_normalised + 1e-6)
term_log2

Target,17-beta-HSD 1,3HIDH,4-1BB,4-1BB ligand,40S ribosomal protein SA,41,4EBP2,6-Phosphogluconate dehydrogenase,6Ckine,ABL1,...,sRAGE,sRANKL,sTie-1,sTie-2,suPAR,tPA,tau,"transcription factor MLR1, isoform CRA_b",uPA,vWF
Accession,,,,,,,,,,,,,,,,,,,,,
GSM6254314,9.374546,8.822097,7.867731,7.468347,11.747036,13.392063,7.786118,12.862764,12.075163,8.129672,...,9.024481,10.418632,13.169784,10.078319,11.397666,10.581127,8.624367,7.539231,10.530869,15.059360
GSM6254315,9.449835,8.978153,8.159926,7.530837,9.969019,13.528320,7.571360,13.145879,12.182038,8.293599,...,10.379428,10.712982,13.393166,9.811600,11.960264,11.170200,7.864872,7.830504,10.346121,14.345101
GSM6254316,9.572084,8.890823,8.119968,7.542441,11.022264,14.942307,7.904536,11.967591,13.043695,8.260804,...,10.530627,10.771967,11.878758,10.100194,11.287662,11.887921,8.342688,7.848884,9.626578,15.251838
GSM6254317,9.564282,9.067161,8.432796,7.692802,10.002551,14.494045,8.801070,12.863569,11.960190,8.465206,...,9.971299,10.687423,12.863007,10.089564,11.753715,11.043910,8.382512,7.909770,10.456552,14.406790
GSM6254318,9.600444,8.960334,8.296035,7.606233,10.286775,13.288196,7.565667,13.362355,12.071793,8.371716,...,11.321706,10.481429,13.240708,10.583838,12.159251,11.616751,8.791973,7.748336,11.233532,15.906615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM6254828,9.565983,9.120282,8.419517,7.931444,10.047035,13.394159,8.053013,14.315650,12.055525,8.776553,...,12.104826,9.659630,12.918895,10.309242,12.240108,11.802791,8.434249,8.047548,10.887481,15.518437
GSM6254829,9.644534,9.335253,8.232436,8.113038,10.029935,13.557583,7.700902,13.694950,12.158752,8.483676,...,10.173972,10.357226,13.149546,10.192939,12.172405,11.528289,8.616490,8.303970,10.786220,14.088064
GSM6254830,9.791671,9.296061,8.408967,8.011645,10.118833,14.175639,7.809322,13.857407,12.399322,8.781062,...,9.546872,10.458548,13.050263,10.316042,12.015814,11.536375,9.059490,8.064398,11.435866,15.277314
GSM6254831,9.398916,9.072281,8.214338,7.755933,9.905733,13.161183,7.777594,14.317454,12.525959,8.417352,...,8.993086,10.695317,12.548211,9.856045,12.003147,10.800942,8.299414,7.897058,10.667682,13.809658
GSM6254832,9.648559,9.432241,8.375657,7.858658,10.087973,13.331422,7.719372,11.370982,12.884956,8.654633,...,8.584407,10.513675,12.903101,10.046818,12.139194,11.040765,9.119058,7.900940,11.041389,15.458274

In [32]:
preterm_data2 = preterm_data[['Accession', 'Target', 'Log2RFU']]
preterm_data3 = preterm_data2.pivot(index = 'Accession', columns = 'Target', values = 'Log2RFU')
preterm_data3

Target,14-3-3,17-beta-HSD 1,3HIDH,4-1BB,4-1BB ligand,40S ribosomal protein SA,41,4EBP2,6-Phosphogluconate dehydrogenase,6Ckine,...,sRAGE,sRANKL,sTie-1,sTie-2,suPAR,tPA,tau,"transcription factor MLR1, isoform CRA_b",uPA,vWF
Accession,,,,,,,,,,,,,,,,,,,,,
GSM4525301,14.831525,11.170238,9.653920,9.025416,8.861087,11.674987,14.086965,8.588340,14.460123,12.809266,...,8.325980,9.116344,14.051090,11.261096,11.984240,9.194264,10.702432,7.892998,11.825992,14.615589
GSM4525302,14.520735,11.102435,10.018757,8.459841,8.861707,11.716777,13.309462,8.510171,14.681238,12.967064,...,8.021813,9.128510,13.890131,11.669151,13.149620,8.557655,10.543515,7.830990,12.381381,15.178474
GSM4525303,14.677549,11.006747,11.205671,8.496654,8.756556,11.791936,13.352016,8.454505,13.735884,13.261566,...,8.406418,9.158610,14.182806,11.456970,13.081899,9.235536,10.610102,7.730640,12.250150,14.926264
GSM4525304,15.159599,10.817383,9.477151,8.798634,9.014299,11.918565,13.766788,8.608440,11.859496,12.866429,...,8.208966,8.970681,14.208173,11.367469,12.378972,8.985842,10.557751,7.889960,11.545882,14.261471
GSM4525305,14.436738,11.155514,10.148731,8.287251,8.747186,11.651097,13.418077,9.310840,14.363457,13.427601,...,8.291861,9.040838,14.232226,11.320631,11.702735,9.638255,10.363587,7.853621,12.006186,15.300192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM4525506,14.815178,10.765120,9.763876,8.540709,8.723490,11.615630,13.796607,8.966073,14.208654,12.937778,...,8.221104,8.917670,14.186161,11.318712,12.417984,8.390169,10.475936,8.224484,11.986304,15.764755
GSM4525507,14.213309,11.029563,10.931328,8.743151,9.342075,11.371396,13.787056,9.581201,13.752861,13.491540,...,8.207014,9.448942,14.851632,11.502882,12.600587,8.990955,10.225930,9.417220,12.764498,13.580718
GSM4525508,14.918868,11.755972,10.272980,8.576295,8.799605,11.605063,13.759191,8.688250,13.940378,12.959857,...,8.584587,8.924219,14.108582,11.055215,12.229269,8.548051,10.369052,7.602884,11.738430,14.816174
GSM4525509,14.681787,11.209027,10.198568,10.191059,9.044394,12.572108,13.900008,8.787250,14.403145,13.060595,...,8.534108,9.084277,14.578591,11.637757,12.505464,8.790511,10.845568,7.908693,12.664092,15.197336
GSM4525510,14.668591,11.013392,9.442529,8.975275,9.094078,11.893150,14.342887,8.610287,12.133817,12.672116,...,8.564531,8.995485,13.924098,11.365502,13.027059,8.575161,10.719817,7.769507,12.205396,15.233395

> Data was log2 transformed before applying machine learning and differential abundance analyses ([Tarca et al., 2021](https://www.sciencedirect.com/science/article/pii/S266637912100166X?via%3Dihub#sec5)).

In [33]:
# Calculate a rowsum (total intensity in each sample)
rowsums = preterm_data3.sum(axis = 1)
rowsums

# Identify the maximum rowsum (maximum total intensity across samples)
max_total = rowsums.max()
max_total

# Normalise the data
preterm_normalised = preterm_data3.div(rowsums, axis = 0).mul(max_total) # normalized_sample = (sample / rowsum) * max_total
preterm_normalised

# Log2 transform the data to stabilise the variance
#preterm_log2 = np.log2(preterm_normalised + 1e-6)
#preterm_log2

Target,14-3-3,17-beta-HSD 1,3HIDH,4-1BB,4-1BB ligand,40S ribosomal protein SA,41,4EBP2,6-Phosphogluconate dehydrogenase,6Ckine,...,sRAGE,sRANKL,sTie-1,sTie-2,suPAR,tPA,tau,"transcription factor MLR1, isoform CRA_b",uPA,vWF
Accession,,,,,,,,,,,,,,,,,,,,,
GSM4525301,15.039422,11.326814,9.789241,9.151928,8.985295,11.838638,14.284426,8.708725,14.662814,12.988816,...,8.442687,9.244130,14.248047,11.418945,12.152226,9.323142,10.852451,8.003636,11.991760,14.820459
GSM4525302,14.625624,11.182632,10.091126,8.520950,8.925719,11.801411,13.405601,8.571643,14.787286,13.060730,...,8.079757,9.194448,13.990465,11.753441,13.244604,8.619470,10.619675,7.887556,12.470816,15.288114
GSM4525303,14.908428,11.179884,11.381938,8.630307,8.894298,11.977425,13.562045,8.587495,13.951951,13.470172,...,8.538651,9.302676,14.405903,11.637190,13.287679,9.380812,10.777000,7.852244,12.442847,15.161055
GSM4525304,15.325044,10.935439,9.580580,8.894658,9.112677,12.048638,13.917031,8.702388,11.988925,13.006847,...,8.298554,9.068583,14.363234,11.491528,12.514070,9.083909,10.672973,7.976067,11.671887,14.417113
GSM4525305,14.627799,11.303151,10.283043,8.396928,8.862950,11.805292,13.595657,9.434064,14.553549,13.605307,...,8.401599,9.160488,14.420581,11.470453,11.857614,9.765812,10.500743,7.957560,12.165081,15.502681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM4525506,15.062374,10.944740,9.926790,8.683214,8.869044,11.809440,14.026808,9.115675,14.445729,13.153649,...,8.358275,9.066465,14.422861,11.507568,12.625182,8.530162,10.650730,8.361712,12.186299,16.027795
GSM4525507,14.358792,11.142458,11.043218,8.832643,9.437697,11.487789,13.928175,9.679270,13.893631,13.629635,...,8.291018,9.545658,15.003648,11.620621,12.729562,9.082983,10.330599,9.513611,12.895151,13.719725
GSM4525508,15.136027,11.927092,10.422513,8.701132,8.927692,11.773986,13.959470,8.814716,14.143294,13.148501,...,8.709544,9.054120,14.313946,11.216134,12.407279,8.672477,10.519984,7.713552,11.909295,15.031838
GSM4525509,14.735968,11.250392,10.236204,10.228667,9.077771,12.618503,13.951304,8.819677,14.456297,13.108792,...,8.565602,9.117801,14.632390,11.680704,12.551613,8.822951,10.885592,7.937878,12.710826,15.253419
GSM4525510,14.852151,11.151212,9.560690,9.087589,9.207879,12.041978,14.522371,8.718034,12.285656,12.830692,...,8.671705,9.108052,14.098341,11.507728,13.190077,8.682469,10.853962,7.866733,12.358132,15.424022

In [40]:
# Combine the term dataset with its metadata
term_log2_long = term_log2.reset_index().melt(id_vars='Accession', var_name='Target', value_name='Log2RFU')
term_log2_long

# Remove the log2RFU col from the filtered term data to be able to merge
filtered_term_data = filtered_term_data.drop(columns = ['Log2RFU']) # hahaha ha ha... 

term_log2_full = pd.merge(term_log2_long, filtered_term_data, on = ['Accession', 'Target'], how = 'inner')
term_log2_full

,Accession,Target,Log2RFU,SeqId,ID_REF,TargetFullName,UniProt,EntrezGeneID,EntrezGeneSymbol,Title,Sample_type,GA,Individual,GEO_accession,Group,GA_delivery
0,GSM6254314,17-beta-HSD 1,9.374546,4708-3,SL004253,Estradiol 17-beta-dehydrogenase 1,P14061,3292,HSD17B1,258633821569_7,protein,25.7,11293,GSE206454,Control,NaN
1,GSM6254315,17-beta-HSD 1,9.449835,4708-3,SL004253,Estradiol 17-beta-dehydrogenase 1,P14061,3292,HSD17B1,258633821572_7,protein,28.4,12820,GSE206454,Control,NaN
2,GSM6254316,17-beta-HSD 1,9.572084,4708-3,SL004253,Estradiol 17-beta-dehydrogenase 1,P14061,3292,HSD17B1,258633821573_6,protein,17.1,14054,GSE206454,Control,NaN
3,GSM6254317,17-beta-HSD 1,9.564282,4708-3,SL004253,Estradiol 17-beta-dehydrogenase 1,P14061,3292,HSD17B1,258633821570_3,protein,30.0,17825,GSE206454,Control,NaN
4,GSM6254318,17-beta-HSD 1,9.600444,4708-3,SL004253,Estradiol 17-beta-dehydrogenase 1,P14061,3292,HSD17B1,258633821569_3,protein,12.3,15468,GSE206454,Control,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753583,GSM6254828,vWF,15.518437,3050-7,SL000017,von Willebrand factor,P04275,7450,VWF,258633818631_4,protein,20.6,14977,GSE206454,Control,NaN
753584,GSM6254829,vWF,14.088064,3050-7,SL000017,von Willebrand factor,P04275,7450,VWF,258633818628_4,protein,17.7,17509,GSE206454,Control,NaN
753585,GSM6254830,vWF,15.277314,3050-7,SL000017,von Willebrand factor,P04275,7450,VWF,258633818627_4,protein,29.3,9900,GSE206454,Control,NaN
753586,GSM6254831,vWF,13.809658,3050-7,SL000017,von Willebrand factor,P04275,7450,VWF,258633818634_3,protein,11.1,13592,GSE206454,Control,NaN
753587,GSM6254832,vWF,15.458274,3050-7,SL000017,von Willebrand factor,P04275,7450,VWF,258633818632_3,protein,37.9,13592,GSE206454,Control,NaN

In [35]:
preterm_data

,Accession,ID_REF,Log2RFU,SeqId,Target,TargetFullName,UniProt,EntrezGeneID,EntrezGeneSymbol,Title,Sample_type,GA,GA_delivery,Group,Individual,GEO_accession
0,GSM4525301,SL000318,12.579057,2182-54_1,C4b,Complement C4b,P0C0L4 P0C0L5,"720,721",C4A C4B,s132,protein,16.9,40.1,Control,10273,GSE150167
1,GSM4525301,SL002662,10.688600,2190-55_1,Coagulation Factor XI,Coagulation Factor XI,P03951,2160,F11,s132,protein,16.9,40.1,Control,10273,GSE150167
2,GSM4525301,SL003168,10.516685,2192-63_10,CTACK,C-C motif chemokine 27,Q9Y4X3,10850,CCL27,s132,protein,16.9,40.1,Control,10273,GSE150167
3,GSM4525301,SL000403,15.616368,2201-17_6,Endostatin,Endostatin,P39060,80781,COL18A1,s132,protein,16.9,40.1,Control,10273,GSE150167
4,GSM4525301,SL000591,8.400026,2211-9_6,TIMP-1,Metalloproteinase inhibitor 1,P01033,7076,TIMP1,s132,protein,16.9,40.1,Control,10273,GSE150167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236245,GSM4525510,SL010516,13.875874,5488-74_3,SRCN1,Proto-oncogene tyrosine-protein kinase Src,P12931,6714,SRC,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236246,GSM4525510,SL010250,13.167904,5489-18_3,Stress-induced-phosphoprotein 1,Stress-induced-phosphoprotein 1,P31948,10963,STIP1,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236247,GSM4525510,SL010384,11.996968,5490-53_3,Testican-1,Testican-1,Q08629,6695,SPOCK1,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236248,GSM4525510,SL010471,9.221829,5491-12_3,Testican-2,Testican-2,Q92563,9806,SPOCK2,s469,protein,29.7,33.3,sPTD,9754,GSE150167
236249,GSM4525510,SL009790,11.028942,5494-52_3,RUXF,Small nuclear ribonucleoprotein F,P62306,6636,SNRPF,s469,protein,29.7,33.3,sPTD,9754,GSE150167

In [ ]:
# Combine the preterm dataset with its metadata
preterm_normalised_long = preterm_normalised.reset_index().melt(id_vars='Accession', var_name='Target', value_name='Log2RFU')
preterm_normalised_long

# Remove the log2RFU col from the filtered term data to be able to merge
preterm_data = preterm_data.drop(columns = ['Log2RFU']) # hahaha ha ha... 

preterm_norm_full = pd.merge(preterm_normalised_long, preterm_data, on = ['Accession', 'Target'], how = 'inner')
preterm_norm_full

,Accession,Target,Log2RFU,ID_REF,SeqId,TargetFullName,UniProt,EntrezGeneID,EntrezGeneSymbol,Title,Sample_type,GA,GA_delivery,Group,Individual,GEO_accession
0,GSM4525301,14-3-3,15.039422,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s132,protein,16.9,40.1,Control,10273,GSE150167
1,GSM4525302,14-3-3,14.625624,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s348,protein,23.0,34.1,sPTD,10877,GSE150167
2,GSM4525303,14-3-3,14.908428,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s226,protein,21.1,36.7,PPROM,10880,GSE150167
3,GSM4525304,14-3-3,15.325044,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s337,protein,20.9,35.0,sPTD,11103,GSE150167
4,GSM4525305,14-3-3,14.627799,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s351,protein,18.7,36.0,sPTD,11170,GSE150167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236245,GSM4525506,vWF,16.027795,SL000017,3050-7_2,von Willebrand factor,P04275,7450,VWF,s500,protein,30.1,33.4,sPTD,9185,GSE150167
236246,GSM4525507,vWF,13.719725,SL000017,3050-7_2,von Willebrand factor,P04275,7450,VWF,s74,protein,27.9,39.0,Control,9228,GSE150167
236247,GSM4525508,vWF,15.031838,SL000017,3050-7_2,von Willebrand factor,P04275,7450,VWF,s385,protein,27.3,30.6,sPTD,9554,GSE150167
236248,GSM4525509,vWF,15.253419,SL000017,3050-7_2,von Willebrand factor,P04275,7450,VWF,s522,protein,28.9,34.7,sPTD,9555,GSE150167
236249,GSM4525510,vWF,15.424022,SL000017,3050-7_2,von Willebrand factor,P04275,7450,VWF,s469,protein,29.7,33.3,sPTD,9754,GSE150167

In [41]:
# Concatenate the two datasets
merged_data = pd.concat([preterm_norm_full, term_log2_full], ignore_index=True)
merged_data

,Accession,Target,Log2RFU,ID_REF,SeqId,TargetFullName,UniProt,EntrezGeneID,EntrezGeneSymbol,Title,Sample_type,GA,GA_delivery,Group,Individual,GEO_accession
0,GSM4525301,14-3-3,15.039422,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s132,protein,16.9,40.1,Control,10273,GSE150167
1,GSM4525302,14-3-3,14.625624,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s348,protein,23.0,34.1,sPTD,10877,GSE150167
2,GSM4525303,14-3-3,14.908428,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s226,protein,21.1,36.7,PPROM,10880,GSE150167
3,GSM4525304,14-3-3,15.325044,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s337,protein,20.9,35.0,sPTD,11103,GSE150167
4,GSM4525305,14-3-3,14.627799,SL017611,4179-57_3,14-3-3 protein family,P31946 P62258 P61981 Q04917 P27348 P63104 P31947,"75,297,531,753,275,300,000,000,000,000",YWHAB YWHAE YWHAG YWHAH YWHAQ YWHAZ SFN,s351,protein,18.7,36.0,sPTD,11170,GSE150167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989833,GSM6254828,vWF,15.518437,SL000017,3050-7,von Willebrand factor,P04275,7450,VWF,258633818631_4,protein,20.6,NaN,Control,14977,GSE206454
989834,GSM6254829,vWF,14.088064,SL000017,3050-7,von Willebrand factor,P04275,7450,VWF,258633818628_4,protein,17.7,NaN,Control,17509,GSE206454
989835,GSM6254830,vWF,15.277314,SL000017,3050-7,von Willebrand factor,P04275,7450,VWF,258633818627_4,protein,29.3,NaN,Control,9900,GSE206454
989836,GSM6254831,vWF,13.809658,SL000017,3050-7,von Willebrand factor,P04275,7450,VWF,258633818634_3,protein,11.1,NaN,Control,13592,GSE206454
989837,GSM6254832,vWF,15.458274,SL000017,3050-7,von Willebrand factor,P04275,7450,VWF,258633818632_3,protein,37.9,NaN,Control,13592,GSE206454

In [43]:
# Export the merged dataset
merged_data.to_csv("../output/tarca_et_al_2021/merged_normalised_datasets_for_modelling.csv", index=False)